trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: packages

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'
    addToPath: true

- task: pipAuthenticate@1
  inputs:
    artifactFeeds: 'Demo Project/demoProjectFeed'

- script: |
    python -m pip install --upgrade pip
    pip install demo-package==1.0.0
  displayName: 'Install package from Azure Artifacts'

- task: Bash@3
  displayName: 'Run Python script'
  inputs:
    targetType: inline
    script: |
      # Add commands to use your package here
      python -c "from demoPackage.greeting import greeting; print(greeting())"
  
