trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- task: TerraformInstaller@1
  displayName: Install Terraform 1.5.5
  inputs:
    terraformVersion: 1.5.5


- script: |
    tfFmtOutput=$(terraform fmt -recursive) 
    if [ -n "$tfFmtOutput" ]; then
      echo "The following files are not properly formatted:"
      echo "$tfFmtOutput"
      exit 1
    else
      echo "All Terraform files are properly formatted."
    fi
  displayName: 'Validate Terraform formatting'
