trigger:
- none

stages:
- stage: example_stage
  displayName: 'Example Stage'
  jobs:
  - job: example_job
    displayName: 'example-job'
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Bash@3 
      displayName: 'Gets hostname'
      inputs:
        targetType: inline
        script: |
          # Identifies the hostname of the agent
          echo "This task is running on agent: $HOSTNAME"
          echo "##vso[task.setvariable variable=hostname]$HOSTNAME"
    - task: Bash@3 
      displayName: 'Gets date'
      inputs:
        targetType: inline
        script: |
          # Gets the current date
          currentDate=$(date +”%m/%d/%Y”)
          echo "Today's date is $currentDate"
          echo "##vso[task.setvariable variable=currentDate]$currentDate"
    - task: Bash@3 
      displayName: 'Uses variables'
      inputs:
        targetType: inline
        script: |
          # Write your commands here
          echo "Today is $(currentDate).  The pipeline $(Build.DefinitionName) is running on $(hostname)."