trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: secretsDemo

steps:
# - task: AzureKeyVault@2
#   displayName: 'Get secret from Key Vault'
#   inputs:
#     azureSubscription: 'ADO-Blogging-SvcCon'  # This is the service connection name
#     KeyVaultName: 'AZ400-SecretsDemo'  # Your Key Vault's name
#     SecretsFilter: 'sendGridApiKey'  # The name of the secret containing the SendGrid API key
#     RunAsPreJob: false

- script: |
    curl --request POST \
    --url https://api.sendgrid.com/v3/mail/send \
    --header "Authorization: Bearer $(sendGridApiKey)" \
    --header 'Content-Type: application/json' \
    --data '{
      "personalizations": [
        {
          "to": [
            {
              "email": "joe@refactored.pro"
            }
          ],
          "subject": "Hello from Azure DevOps"
        }
      ],
      "from": {
        "email": "joe@refactored.pro"
      },
      "content": [
        {
          "type": "text/plain",
          "value": "This is a test email sent from an Azure DevOps 'Secrets-Demo' pipeline."
        }
      ]
    }'
  displayName: 'Send email via SendGrid'
